script: "./scripts/build.sh"
branches:
  only:
    - master
    - live
deploy:
- provider: s3
  region: eu-west-2
  bucket: crossword-builds
  upload-dir: "$TRAVIS_REPO_SLUG/test/$TRAVIS_COMMIT"
  local_dir: "./dist"
  skip_cleanup: true
  on:
    branch: master
- provider: s3
  region: eu-west-2
  bucket: crosswords-bucket-test
  local_dir: "./dist/public"
  skip_cleanup: true
  on:
    branch: master
- provider: lambda
  function_name: crosswordApi-test
  region: eu-west-2
  role: arn:aws:iam::055700101518:role/service-role/crosswordApiLambda
  runtime: nodejs6.10
  handler_name: handler
  module_name: bundle.lambda
  zip: "$TRAVIS_BUILD_DIR/dist/bundle.lambda.js"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: lfDmcKbPRegQTNDdTnEMH/+MQsGekclAkPv5dJ6f/RnOR8ACFkQMsDZomOA0LLWM+S7PuKgvbrVr6nnC40ic2/V4v45/SFP2Pl+UwrDy6S7FievrPX/tDLpOKPZGhSxKzM29E5j2ErUyG2BQ/QMzTvaq0PySDWHKdmv92/rc6wg128v4qn7y4HGMYG/JFjY4K1cF2IcyFA36fPeDKZRd54wpoiH2UeDmprKyrquI9ie1cJazv5L78fUzMVX8PYhNBxZwhZSS2sO8gioQcDg6FxWIzrXXuNL6c2OwRPD4NThL0Em18Di+z3pZ/SGHgnP682Be51LV8tUlzMF7viuqqd2gogPjmyAxmgJpWT714anAQg348J53j0geHvaRAkSK+876sV2vv0C0kGKKa29+LQMR4JCxhLcO1xDfABjjhouglcAOVNVwPyFo1T2Sx3GBlrIdzo8syN2BTMnAKCzVfnMLdErkgaxTzfvsv7ioG4bXOVy0xZbyrATfwMOQglL95eSwC1SkcgqjSZrVdl9TvqvOAXVxG0ntXBhmZgCKPn2UAO9wappDKPNnC0rkdzSqK+QJeABfGXNaqgIIKhIfltYLtOGt5pWt0yRc8BpjQClTSvMtoyVOuTaPvAW7hQ/sjE6s+gejtFiNkjKs2ur4mw+f8QQgbHpaKOH2hLCdiOo=
  - secure: FxchKc3FpUvYiWWefogiDxgWdQM4Xdi2//bgWobNprCbW95ZFtH7NVSmgoyoDRgQ/wpKiIDjufmmGE+X2/efJL//JuK7QSFlQRp7ZcA+p8LhQMSHRGfyOZnp7f3b4jEOVRaxw1I+5n9f0gjbHN1mpJjRfcuee3zitlfrATSkDZHaxdMQP1rHAzu1q0zfnhSzUjk/aVbiK5MfmzjY4eGhgrwUxvBVuEIgSY+AaJ0aTAEx6fQPVUD7uYGw76v6mv6aOEs0DjhCQQHN1noeuiJAGWjxGSfdz6pBj+GBHErt3Yx9h/cvGER4dXbivPFbzasEN6qTUUsoInqasBEMZ2cf0WyuUq+mHrLfpjeCTLuijSltEF/S/QrS9imrw+2ChuTa7rEzbhXAS/XvfivBRLv2YdgXSAaoZ4qalaYxYKw0ZY4IbDVoi8ffoMfgCn0fGjnbZvPlqC35b4bCSznr660tSHyvyHcLN1Lp6+sb69BBA3nJsxdIZ3VJAlynVL1uulAyt2aqkyiDhdPEPc3uY1d9FsbDx/RUaHTCXWocRU7fB+EqY9WdmmC3gM/Tcfr/N3+/iy9VN3aO9YBstmbvfWK9bz+B5f4aSqSXo/9v25VZrkuy9uw+k20XlCbWn8J1/8xAxSnqM6eV3ps9aSUCHSrFIzK6CWi6/42pMRR/HeK6oEU=
